# compose.prod.yml

# $docker compose -f compose.yml -f compose.prod.yml -p aeat_prod up --build

version: '3.8'

services:
  db:
    volumes:
      - aeatbe-data-prod:/var/lib/mysql  # 볼륨 연결
    ports: []
    deploy:
      resources:
        limits:
          memory: ${DB_CONTAINER_MAX_MEM}
 
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile  # Dockerfile 파일 경로
    image: ${SPRING_IMAGE_NAME}
    container_name: ${SPRING_CONTAINER_NAME}
    deploy:
      resources:
        limits:
          memory: ${SPRING_CONTAINER_MAX_MEM}
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_CONTAINER_NAME}:3306${DB_NAME}${DB_PARAMS}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      JAVA_MIN_MEM: ${JAVA_MIN_MEM}
      JAVA_MAX_MEM: ${JAVA_MAX_MEM}
      JAVA_MAX_METASPACE: ${JAVA_MAX_METASPACE}
    ports:
      - ${SPRING_HOST_PORT}:${SPRING_CONTAINER_PORT}

volumes:
  aeatbe-data-prod:
    driver: local
