services:
  db:
    image: mysql:latest  #MySQL 이미지 버전맞춰서하면될듯
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u user --password=password" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']